version: '3'
services:
  postgres-order:
    image: postgres:latest
    environment:
      POSTGRES_DB: microservice_db_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3572
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  postgres-document:
    image: postgres:latest
    environment:
      POSTGRES_DB: microservice_db_document
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3572
      POSTGRES_PORT: 5433 # Порт базы данных внутри контейнера
    command: [ "-p", "5433" ]
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  rabbitmq:
    image: "rabbitmq:management"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app

  app_order:
    build:
      context: /app_order
      dockerfile: /Dockerfile_Ord
    ports:
      - "80:80"
    depends_on:
      - postgres-order
      - rabbitmq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - app

  app_document:
    build:
      context: /app_document
      dockerfile: /Dockerfile_Doc
    ports:
      - "81:81"
    depends_on:
      - postgres-document
      - rabbitmq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - app


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app

networks:
  app:
  # name: app
volumes:
  postgres_data: